### PR TITLE
Broaden reg-ex to all resolver variants

### PR DESCRIPTION
**Pull request by katrinleinweber**
Hello :-)

The DOI foundation recommends [this new, secure resolver](https://www.doi.org/doi_handbook/3_Resolution.html#3.8). Accordingly, this PR updates the docu, reg-exes and tests.

Cheers!

### CODE REVIEW

**Comment by RichardLitt** [comment]
Fantastic! Thank you, @katrinleinweber!

**Comment by katrinleinweber** [comment]
You're welcome, and thanks for merging :-)

**Comment by RichardLitt** [comment]
There's a failed test; I think it's probably unrelated? What do you think?

**Comment by katrinleinweber** [comment]
Ah, I think it's related. Best `git revert 7e64e2dfdc96627a9e1d725fa0392709bed0d339` for now, in case the reason is not obvious.

**Comment by RichardLitt** [comment]
Reverted. Let me know if you'd like to submit a PR to fix it!

**Pull request merged**
